# Decathlon Data Analytics Project

## 1. Database Connection

This notebook establishes a connection between Python and
Microsoft SQL Server.

**Database:** DecathlonDB

**Purpose:** Verify the database connection before performing
data exploration and business analysis.

### Import libraries

In [3]:
import pyodbc
import pandas as pd

### Configure the connection

In [4]:
import pyodbc

DRIVER_NAME = 'SQL Server'
SERVER_NAME = r'NASIRS-LAPTOP\SQLEXPRESS'
DATABASE_NAME = 'DecathlonDB'

connection_string = (
    f'DRIVER={{{DRIVER_NAME}}};'
    f'SERVER={SERVER_NAME};'
    f'DATABASE={DATABASE_NAME};'
    'Trusted_Connection=yes;'
)

### Establish the connection

In [5]:
conn = pyodbc.connect(connection_string)

print("Connected successfully!")

Connected successfully!

### Verify the database

In [6]:
cursor = conn.cursor()

cursor.execute("SELECT DB_NAME()")

print("Connected Database:", cursor.fetchone()[0])

Connected Database: DecathlonDB

### Verify the available tables

In [7]:
query = """
SELECT
    TABLE_SCHEMA,
    TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_SCHEMA, TABLE_NAME;
"""

tables = pd.read_sql_query(query, conn)

tables

C:\Users\nasir\AppData\Local\Temp\ipykernel_13420\450349885.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tables = pd.read_sql_query(query, conn)

  TABLE_SCHEMA TABLE_NAME
0          dbo   products
1          dbo      sales
2          dbo      store

In [8]:
query = "SELECT TOP 10 * FROM dbo.products"

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

('P0001', 'Running Shoes Essential Black (Demo)', 'Running', 'Running Shoes', 'Kalenji', 'Essential', 'Black', 1599.0, 1012.0)
('P0002', 'Running Shoes Essential Blue (Demo)', 'Running', 'Running Shoes', 'Kalenji', 'Essential', 'Blue', 1799.0, 1102.0)
('P0003', 'Running Shoes Active Black (Demo)', 'Running', 'Running Shoes', 'Kalenji', 'Active', 'Black', 1999.0, 1050.0)
('P0004', 'Running Shoes Active Blue (Demo)', 'Running', 'Running Shoes', 'Kalenji', 'Active', 'Blue', 2299.0, 1559.0)
('P0005', 'Running Shoes Performance Black (Demo)', 'Running', 'Running Shoes', 'Kalenji', 'Performance', 'Black', 2799.0, 1768.0)
('P0006', 'Running Shoes Performance Blue (Demo)', 'Running', 'Running Shoes', 'Kalenji', 'Performance', 'Blue', 3399.0, 1905.0)
('P0007', 'Running T-Shirt Essential Black (Demo)', 'Running', 'Running T-Shirt', 'Kalenji', 'Essential', 'Black', 499.0, 292.0)
('P0008', 'Running T-Shirt Essential Blue (Demo)', 'Running', 'Running T-Shirt', 'Kalenji', 'Essential', 'Blue', 499.0, 332.0)
('P0009', 'Running T-Shirt Active Black (Demo)', 'Running', 'Running T-Shirt', 'Kalenji', 'Active', 'Black', 599.0, 371.0)
('P0010', 'Running T-Shirt Active Blue (Demo)', 'Running', 'Running T-Shirt', 'Kalenji', 'Active', 'Blue', 699.0, 379.0)

In [29]:
query = "SELECT * FROM dbo.products"

products_data = pd.read_sql_query(query, conn)

products_data.head()

C:\Users\nasir\AppData\Local\Temp\ipykernel_29012\716573735.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products_data = pd.read_sql_query(query, conn)

,Product_Key,Product_Name,Sport,Product_Type,Brand_Label,Product_Tier,Colour,Base_List_Price_INR,Base_Unit_Cost_INR
0,P0001,Running Shoes Essential Black (Demo),Running,Running Shoes,Kalenji,Essential,Black,1599.0,1012.0
1,P0002,Running Shoes Essential Blue (Demo),Running,Running Shoes,Kalenji,Essential,Blue,1799.0,1102.0
2,P0003,Running Shoes Active Black (Demo),Running,Running Shoes,Kalenji,Active,Black,1999.0,1050.0
3,P0004,Running Shoes Active Blue (Demo),Running,Running Shoes,Kalenji,Active,Blue,2299.0,1559.0
4,P0005,Running Shoes Performance Black (Demo),Running,Running Shoes,Kalenji,Performance,Black,2799.0,1768.0

In [9]:
query = "SELECT * FROM dbo.sales"

salesdata = pd.read_sql_query(query, conn)

salesdata.head()

C:\Users\nasir\AppData\Local\Temp\ipykernel_13420\695504608.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  salesdata = pd.read_sql_query(query, conn)

,Sale_Line_ID,Order_ID,Purchase_Date,Product_ID,Store_ID,Channel,Payment_Method,Order_Hour,Promotion,Quantity,...,Discount_Pct,Gross_Sales_INR,Discount_INR,Sales_Before_Returns_INR,Returned_Qty,Refund_INR,Net_Sales_INR,Net_COGS_INR,Gross_Profit_INR,Return_Reason
0,SL000001,ORD000001,2025-01-01,P0193,S030,In Store,UPI,19,None,1,...,0%,799.0,0.0,799.0,0,0.0,799.0,515.0,284.0,Not Returned
1,SL000002,ORD000001,2025-01-01,P0111,S030,In Store,UPI,19,None,1,...,0%,299.0,0.0,299.0,0,0.0,299.0,178.0,121.0,Not Returned
2,SL000003,ORD000001,2025-01-01,P0211,S030,In Store,UPI,19,None,1,...,0%,199.0,0.0,199.0,0,0.0,199.0,112.0,87.0,Not Returned
3,SL000004,ORD000002,2025-01-01,P0065,S001,In Store,Credit Card,20,None,1,...,0%,999.0,0.0,999.0,0,0.0,999.0,547.0,452.0,Not Returned
4,SL000005,ORD000002,2025-01-01,P0223,S001,In Store,Credit Card,20,None,2,...,0%,798.0,0.0,798.0,0,0.0,798.0,432.0,366.0,Not Returned

In [10]:
salesdata.shape

(84000, 22)

In [11]:
query = "SELECT * FROM dbo.store"

store_data = pd.read_sql_query(query, conn)

store_data.head()

C:\Users\nasir\AppData\Local\Temp\ipykernel_13420\2713816091.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  store_data = pd.read_sql_query(query, conn)

,Store_Key,Store_Name,City,State,Region,Country,Store_Format,Floor_Area_Sqm
0,S001,Demo Mumbai Sports Store,Mumbai,Maharashtra,West,India,Large Format,4900
1,S002,Demo Pune Sports Store,Pune,Maharashtra,West,India,Standard,3800
2,S003,Demo Nashik Sports Store,Nashik,Maharashtra,West,India,Standard,2600
3,S004,Demo Nagpur Sports Store,Nagpur,Maharashtra,West,India,Standard,2400
4,S005,Demo Ahmedabad Sports Store,Ahmedabad,Gujarat,West,India,Large Format,1900

In [13]:
from src.database import get_connection

conn = get_connection()

print("Database connected successfully!")

ModuleNotFoundError: No module named 'src'

In [14]:
import os

print(os.getcwd())

c:\Users\nasir\OneDrive\Desktop\Portfolio Projects\Decathlon-Data-Analytics\notebooks

In [15]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.database import get_connection

conn = get_connection()

print("Database connected successfully!")

Database connected successfully!

In [16]:
cursor = conn.cursor()
cursor.execute("SELECT DB_NAME()")

print("Connected database:", cursor.fetchone()[0])

Connected database: DecathlonDB